### ISSUE TITLE
Can the serve task be used for "normal" node scripts?

### ISSUE THREAD

**Issue by arichiardi** [degree9/boot-nodejs#9]
Hello @flyboarder!

I am looking into this for launching a nodejs script automatically when using `boot-figreload` with `:target :nodejs`. I was wondering if `serve` can actually launch a normal script and if so whether it is a good idea to rename it to something else like `node` or `launch`?

I am going to try anyway and sorry if this is more like a usage question!

**Comment by burn2delete** [comment]
Yes! serve works with any nodejs script.

**Comment by burn2delete** [comment]
Closing as there is currently no action - task names will be reviewed.
